name: tuanlv-test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.KEY }}
            HOSTNAME: ${{secrets.HOST}}
            USER_NAME: ${{secrets.USERNAME}}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ls -la
          ssh -oKexAlgorithms=+diffie-hellman-group1-sha1 -oHostKeyAlgorithms=+ssh-dss -o StrictHostKeyChecking=no -i private_key ec2-user@54.172.252
